language: php

env:
  - CODACY_PROJECT_TOKEN=3de3502cbaca4ee0aa09426b21e172c0

php:
  - 7.3

os:
  - linux

before_script:
  composer install --prefer-source --no-interaction
  
after_success:
  - bash <(curl -s https://codecov.io/bash)